// Sync Inbox – JSON Schema
// Constraint: §4.4 UUIDv7 mandatory. UUIDv4 and auto-incrementals prohibited.
// UUIDv7 regex: version nibble = 7, variant bits = 8/9/a/b

export const syncInboxSchema = {
  body: {
    type: 'object',
    required: ['id', 'tenant_id', 'payload'],
    additionalProperties: false,  // CLNT.CR.03 – strict, no extra fields
    properties: {
      id: {
        type: 'string',
        pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
        description: 'UUIDv7 generated by client',
      },
      tenant_id: {
        type: 'string',
        format: 'uuid',
      },
      payload: {
        type: 'object',
        minProperties: 1,
      },
    },
  },
};
