-- 002_tenants.sql
-- Multi-tenant root table. All operational tables reference this via FK.
-- Constraint: §4.4 UUIDv7 mandatory, §4.5 RLS isolation.

CREATE TABLE IF NOT EXISTS tenants (
  id         UUID PRIMARY KEY,  -- UUIDv7 generated by client
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ          -- Soft-delete pattern (DB.IN.04)
);

-- Prevent mutation of audit timestamps (DB.CR.03)
CREATE OR REPLACE FUNCTION prevent_created_at_update()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.created_at IS DISTINCT FROM NEW.created_at THEN
    RAISE EXCEPTION 'Mutation of created_at is prohibited';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tenants_protect_created_at
  BEFORE UPDATE ON tenants
  FOR EACH ROW
  EXECUTE FUNCTION prevent_created_at_update();
